### PR TITLE
Added Download (as PNG) Button

### PR DESCRIPTION
**Pull request by effacestudios**
image

### CODE REVIEW

**Comment by Zarkonnen** [comment]
Thank you, this is really cool!

**Comment by ghost** [comment]
Excellent! Thank you for adding this much needed feature!

**Comment by ghost** [comment]
I tried it out and felt like it wasn't that good. This is the result it gives:

https://imagehost.imageupload.net/2020/04/23/Planet.png

The resulting image is low resolution and does not seperate the black background to transparent properly. I could get a better result by simply using the Snipping Tool or just making a regular screenshot. I feel dissapointed. : (

**Comment by Zarkonnen** [comment]
I'm working on improvements. I'll see if I can get the transparency to work.

**Comment by Zarkonnen** [comment]
(The higher resolution is comparatively straightforward.)

**Pull request merged**
